[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  framework = "#auto"
  targetPort = 5173
  port = 8888
  publish = "dist"
  autoLaunch = false

[context.dev.environment]
  VITE_API_URL = "/api"

[[redirects]]
  from = "/api/*"
  to = "https://basesports-production.up.railway.app/api/:splat"
  status = 200
  force = true
